/*
 * WARNING!
 *
 * This file was generated by the following autogen template:
 *
 * src/redux/modules/appReducers.ts.hbs
 *
 * Do not modify, as any changes will be overwritten!
 */

import { reducer as auth } from './auth';
import { reducer as users } from './users';

export const appReducers = {
  auth,
  users,
};
