/*
 * WARNING!
 *
 * This file was generated by the following autogen template:
 *
 * src/redux/modules/appTypes.ts.hbs
 *
 * Do not modify, as any changes will be overwritten!
 */

import { AuthAction, AuthState } from './auth';
import { UsersAction, UsersState } from './users';

export type AppAction =
  | AuthAction
  | UsersAction

export interface AppState {
  auth: AuthState;
  users: UsersState;
}
